apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: orderservice-v1
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orderservice-v1
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: orderservice-v2
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orderservice-v2
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
