apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-user
  namespace: kubernetes-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-monitoring
rules:
- apiGroups: ["*"]
  resources: ["namespaces", "deployments", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring
subjects:
- kind: ServiceAccount
  name: monitoring-user
  namespace: kubernetes-dashboard
